define({

    guests: [
        { name: 'n1', sex: 'f', hobby: 'h3' },
        { name: 'n1', sex: 'f', hobby: 'h1' },
        { name: 'n1', sex: 'f', hobby: 'h2' },
        { name: 'n2', sex: 'f', hobby: 'h3' },
        { name: 'n2', sex: 'f', hobby: 'h2' },
        { name: 'n3', sex: 'm', hobby: 'h1' },
        { name: 'n3', sex: 'm', hobby: 'h3' },
        { name: 'n4', sex: 'm', hobby: 'h2' },
        { name: 'n4', sex: 'm', hobby: 'h1' },
        { name: 'n5', sex: 'm', hobby: 'h2' },
        { name: 'n5', sex: 'm', hobby: 'h3' },
        { name: 'n6', sex: 'm', hobby: 'h2' },
        { name: 'n6', sex: 'm', hobby: 'h1' },
        { name: 'n7', sex: 'f', hobby: 'h2' },
        { name: 'n7', sex: 'f', hobby: 'h1' },
        { name: 'n7', sex: 'f', hobby: 'h3' },
        { name: 'n8', sex: 'f', hobby: 'h3' },
        { name: 'n8', sex: 'f', hobby: 'h2' },
        { name: 'n9', sex: 'f', hobby: 'h1' },
        { name: 'n9', sex: 'f', hobby: 'h3' },
        { name: 'n9', sex: 'f', hobby: 'h2' },
        { name: 'n10', sex: 'm', hobby: 'h2' },
        { name: 'n10', sex: 'm', hobby: 'h3' },
        { name: 'n11', sex: 'm', hobby: 'h3' },
        { name: 'n11', sex: 'm', hobby: 'h2' },
        { name: 'n11', sex: 'm', hobby: 'h1' },
        { name: 'n12', sex: 'm', hobby: 'h3' },
        { name: 'n12', sex: 'm', hobby: 'h1' },
        { name: 'n13', sex: 'm', hobby: 'h2' },
        { name: 'n13', sex: 'm', hobby: 'h3' },
        { name: 'n13', sex: 'm', hobby: 'h1' },
        { name: 'n14', sex: 'f', hobby: 'h3' },
        { name: 'n14', sex: 'f', hobby: 'h1' },
        { name: 'n15', sex: 'f', hobby: 'h3' },
        { name: 'n15', sex: 'f', hobby: 'h1' },
        { name: 'n15', sex: 'f', hobby: 'h2' },
        { name: 'n16', sex: 'f', hobby: 'h3' },
        { name: 'n16', sex: 'f', hobby: 'h2' },
        { name: 'n16', sex: 'f', hobby: 'h1' }
    ],

    seat: { seat: 16 },
    start: { state: 'start' }
});